### ISSUE TITLE
Results Page

### ISSUE THREAD

**Issue by eleopold** [MTUHIDE/ask-meagain#14]
Basic Layout of the results page. 
HTML/CSS only. 
Try to make it as modular as possible.

Ignore:
Colors

**Comment by Daniel-Rutkowski** [comment]
![chart1](https://user-images.githubusercontent.com/20327617/46919570-05e63700-cfaf-11e8-8b1e-febd524a39e1.PNG)

The chart has been completed and is responsive (if you refresh the page), but I couldn't remember the exact specifications from the 3 rectangles on the side of the wire frame from Figma. @msexauer Could you remind me?
